// src/components/MatchList.tsx
import { useState } from "react";
import { Accordion } from "@/components/ui/accordion";
import { Skeleton } from "@/components/ui/skeleton";
import { MatchCard } from "./MatchCard";
import type { MatchDTO, UserChoice } from "@/types";
import type { PredictionState } from "./hooks/usePredictions";

interface MatchListProps {
  matches: MatchDTO[];
  isLoading: boolean;
  predictionsState: Record<string, PredictionState>;
  isAuthenticated: boolean;
  onGeneratePrediction: (match: MatchDTO) => void;
  onSavePrediction: (matchId: string, note: string | null, userChoice: UserChoice | null) => void;
}

export function MatchList({
  matches,
  isLoading,
  predictionsState,
  isAuthenticated,
  onGeneratePrediction,
  onSavePrediction,
}: MatchListProps) {
  const [openedMatches, setOpenedMatches] = useState<Set<string>>(new Set());

  const handleAccordionChange = (value: string) => {
    if (value) {
      const match = matches.find((m) => m.id === value);
      if (match) {
        const predictionState = predictionsState[value];
        if (!openedMatches.has(value) || predictionState?.status === "error") {
          if (!predictionState || predictionState.status === "idle" || predictionState.status === "error") {
            onGeneratePrediction(match);
          }
          if (!openedMatches.has(value)) {
            setOpenedMatches(new Set([...openedMatches, value]));
          }
        }
      }
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-4">
        {Array.from({ length: 5 }).map((_, index) => (
          <div key={index} className="border rounded-lg bg-card p-4 sm:p-6">
            <div className="flex flex-col gap-3">
              <Skeleton className="h-4 w-40 mx-auto" />
              <div className="flex items-center justify-center gap-4">
                <Skeleton className="h-5 w-24 sm:w-32" />
                <Skeleton className="h-6 w-6 sm:h-8 sm:w-8 rounded-full" />
                <Skeleton className="h-3 w-8" />
                <Skeleton className="h-6 w-6 sm:h-8 sm:w-8 rounded-full" />
                <Skeleton className="h-5 w-24 sm:w-32" />
              </div>
              <Skeleton className="h-3 w-32 mx-auto" />
            </div>
          </div>
        ))}
      </div>
    );
  }

  return (
    <Accordion type="single" collapsible className="space-y-4" onValueChange={handleAccordionChange}>
      {matches.map((match) => (
        <MatchCard
          key={match.id}
          match={match}
          predictionState={predictionsState[match.id]}
          isAuthenticated={isAuthenticated}
          onSavePrediction={onSavePrediction}
        />
      ))}
    </Accordion>
  );
}

// src/components/MatchList.vue
<script setup lang="ts">
import { ref } from "vue";
import { Accordion } from "@/components/ui/accordion";
import { Skeleton } from "@/components/ui/skeleton";
import MatchCard from "./MatchCard.vue";
import type { MatchDTO, UserChoice } from "@/types";
import type { PredictionState } from "./hooks/usePredictions";

const props = defineProps<{
  matches: MatchDTO[];
  isLoading: boolean;
  predictionsState: Record<string, PredictionState>;
  isAuthenticated: boolean;
}>();

const emit = defineEmits<{
  generatePrediction: [match: MatchDTO];
  savePrediction: [matchId: string, note: string | null, userChoice: UserChoice | null];
}>();

const openedMatches = ref<Set<string>>(new Set());

const handleAccordionChange = (value: string | string[] | undefined) => {
  if (typeof value === "string" && value) {
    const match = props.matches.find((m) => m.id === value);
    if (match) {
      const predictionState = props.predictionsState[value];
      if (!openedMatches.value.has(value) || predictionState?.status === "error") {
        if (!predictionState || predictionState.status === "idle" || predictionState.status === "error") {
          emit("generatePrediction", match);
        }
        if (!openedMatches.value.has(value)) {
          openedMatches.value = new Set([...openedMatches.value, value]);
        }
      }
    }
  }
};
</script>

<template>
  <div v-if="isLoading" class="space-y-4">
    <div v-for="index in 5" :key="index" class="border rounded-lg bg-card p-4 sm:p-6">
      <div class="flex flex-col gap-3">
        <Skeleton class="h-4 w-40 mx-auto" />
        <div class="flex items-center justify-center gap-4">
          <Skeleton class="h-5 w-24 sm:w-32" />
          <Skeleton class="h-6 w-6 sm:h-8 sm:w-8 rounded-full" />
          <Skeleton class="h-3 w-8" />
          <Skeleton class="h-6 w-6 sm:h-8 sm:w-8 rounded-full" />
          <Skeleton class="h-5 w-24 sm:w-32" />
        </div>
        <Skeleton class="h-3 w-32 mx-auto" />
      </div>
    </div>
  </div>

  <Accordion v-else type="single" collapsible class="space-y-4" @update:model-value="handleAccordionChange">
    <MatchCard
      v-for="match in matches"
      :key="match.id"
      :match="match"
      :prediction-state="predictionsState[match.id]"
      :is-authenticated="isAuthenticated"
      @save="(matchId, note, choice) => emit('savePrediction', matchId, note, choice)"
    />
  </Accordion>
</template>
